apiVersion: v1
kind: ConfigMap
metadata:
  name: nginconfig
data:
  nginx.conf: |
    # user www-data;
              worker_processes auto;
              pid /run/nginx.pid;

              events {
              worker_connections 1024;
              }

              http {
                      include       mime.types;
                       server {
                          listen 80;
                          server_name localhost 127.0.0.1;

                         location / {
                               root /usr/share/nginx/html;
                               index index.html;
                               try_files $uri $uri/ /index.html;
                                if (!-e $request_filename){
                                  rewrite ^(.*)$ /index.html break;
                                }
                              }

                              location  /api {
                              proxy_pass          http://vco-api-server:3012;
                              proxy_set_header    X-Forwarded-For $remote_addr;
                          }


                      }
                   }
