apiVersion: v1
kind: ConfigMap
metadata:
  name: env-dev-config  
data:
  .env.development: |
    PORT=3012
                    SESSION_SECRET=ashdfjhakdlkjfhalwsdjhflak
                    CRYPTO_SECRET=sda46ufgh239d7fjhwi2sejhrgw4ersjdf8u7eweoi42hg0siojg
                    # MAILGUN_APIKEY=
                    # MAILGUN_DOMAIN=
                    #MONGODB_URI=mongodb://db:6vmfhqlwussld@13.55.172.91/provisioning-dev
                    MONGODB_URI=mongodb://vcodbuser:HDL98XB8hpW@10.9.0.3/provisioning-dev?authSource=admin&w=1
                    #MONGODB_URI=mongodb://b111.dynu.net:8917/provisioning-dev
                    EXPORT_DIR=prj/optus/gap-data/exported-dev/
                    COMMAND_DIR=prj/optus/gap-data/income-dev/
                    #EXPORT_DIR=prj/optus/gap-data/income-dev/
                    HISTORY_LOG_DIR=prj/optus/gap-data/mail-log-dev/
                    #HISTORY_LOG_DIR=/home/mihan/Desktop/
                    CHANGE_LOG_DIR=prj/optus/gap-data/change-log-dev/
                    TEMP_DIR=prj/optus/gap-data/temp-dev/

                    # commend this 4 and add our ones, (gmail)
                    MAIL_SERVICE_HOST=smtp.gmail.com
                    MAIL_SERVICE_PORT=25
                    MAIL_SERVICE=gmail
                    # sender
                    MAIL_AUTH_USER=onboard.2912@gmail.com
                    # sender password
                    MAIL_AUTH_PASS=VCOTesting123
                    # auth method
                    MAIL_AUTH_METHOD=PLAIN
                    # RECEIVER
                    MAIL_TEST_RECEIVER=onboard.2912@gmail.com

                    MAIL_CC_LIST=alfred.alfie123@gmail.com
                    MAIL_ALERT_CC_LIST=alfred.alfie@jinformation.net,alfred.alfie123@gmail.com
                    #MAIL_AUTH_USER=optus.networks.oss@gmail.com
                    #MAIL_AUTH_PASS=Today123
                    INTEGRATION_SERVICE=http://localhost:3003
                    BASE_URL=http://localhost:3000
                    OPTUS_APPROVAL_BASE_URL=http://localhost:3012

                    IS_PORT=3003
                    #IS_MONGODB_URI=mongodb://localhost:27017/gpm-is
                    INCOME_DIR=prj/optus/gap-data/income-dev
                    INPROGRESS_DIR=prj/optus/gap-data/inprogress-dev
                    RESULT_DIR=prj/optus/gap-data/result-dev
                    RESOURCE_DIR=prj/optus/gap-data/resource-dev

                    # Jira connection related properties
                    JIRA_PROTOCOL=https
                    JIRA_HOST=ossdevdefects.atlassian.net
                    JIRA_PORT=443
                    JIRA_USER=tsaasp@gmail.com
                    # use api token instead of password
                    JIRA_PASSWORD=QE26b5YAY6Gs8Qwqiv8wDD9F
                    JIRA_API_VERSION=3
                    JIRA_CONNECT_STRICT_SSL=true
                    JIRA_GROUP_NAME=Genesis Account Provisioning Nokia
                    JIRA_ADD_PROJECT_KEY=GAP
                    JIRA_REVOKE_PROJECT_KEY=GPP
                    #JIRA_PROTOCOL=http
                    #JIRA_HOST=gdwgnpappl002.optus.com.au
                    #JIRA_PORT=8180
                    #JIRA_USER=cp558846
                    #JIRA_PASSWORD=Gustmd12#
                    #JIRA_API_VERSION=2
                    INTEGRATION_MODE=simulation
                    LDAP_URL=ldap://sydhubdcs.optus.com.au:389
                    LDAP_USERNAME=cp558846
                    LDAP_PASSWORD=Gustmd12#
                    #LOGIN_METHOD=local
                    LOGIN_METHOD=ldap
                    IS_CLICK_FINAL_BUTTON=
                    HEADLESS_MODE=1
                    #VCO
                    SIMULATION_EMPID=CP698366
                    VDI_AUTOMATION_RESULT=prj/optus/gap-data/vdi-result-dev
                    UAM_REPORT_DIR=prj/optus/gap-data/uam-report-dev
                    UAM_FETCH_RESULT=prj/optus/gap-data/uam-report-dev/uamResultFetch.json
                    TIME_TO_GET_UAM_UPDATE=1 minute
                    TIME_TO_GET_CRIMS_UPDATE=2 hours
                    TIME_TO_UPDATE_ACCOUNT_CREATION_STATUS=2 minutes
                    TIME_TO_GENERATE_SOW=1 minute
                    TIME_TO_GET_SOW_RESPONSE=2 minutes
                    TIME_TO_CREATE_VDI_ACCOUNT_JOBS=1 minute
                    TIME_TO_CREATE_VDI_ACCOUNT=in 60 minutes
                    TIME_TO_CREATE_APPLICATION_ACCOUNT=1 minute
                    TIME_TO_CREATE_SM9_JIRA=2 minutes
                    TIME_TO_UPDATE_PADLOCK_STATUS=1 minute
                    TIME_TO_CHECK_APPROVE_MANAGER_EXCEEDS_5_DAYS=24 hours

                    PADLOCK_BASE_URL=https://10.118.3.121:443
                    PADLOCK_X_USERNAME=vco-padlock
                    PADLOCK_X_PASSWORD=$2y$12$AxIpgL.F0svuFHgqLeHIVeFUbQpiTSDAPQ.y.2WLSdw82WIXpJguq
                      # Processing user failed from UAM System: Jira task creation properties
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-prod-config   
data:
  .env.production: |
    PORT=3012
                   SESSION_SECRET=ashdfjhakdlkjfhalwsdjhflak
                   CRYPTO_SECRET=sda46ufgh239d7fjhwi2sejhrgw4ersjdf8u7eweoi42hg0siojg
                   # MAILGUN_APIKEY=
                    # MAILGUN_DOMAIN=
                       #MONGODB_URI=mongodb://db:6vmfhqlwussld@13.55.172.91/provisioning-dev
                   MONGODB_URI=mongodb://vcodbuser:HDL98XB8hpW@10.9.0.3:27017/provisioning-dev?authSource=admin&w=1
                    #MONGODB_URI=mongodb://b111.dynu.net:8917/provisioning-dev
                   EXPORT_DIR=prj/optus/gap-data/exported-dev/
                   COMMAND_DIR=prj/optus/gap-data/income-dev/
                     #EXPORT_DIR=prj/optus/gap-data/income-dev/
                   HISTORY_LOG_DIR=prj/optus/gap-data/mail-log-dev/
                   #HISTORY_LOG_DIR=/home/mihan/Desktop/
                   CHANGE_LOG_DIR=prj/optus/gap-data/change-log-dev/
                   TEMP_DIR=prj/optus/gap-data/temp-dev/

                    # commend this 4 and add our ones, (gmail)
                   MAIL_SERVICE_HOST=smtp.gmail.com
                   MAIL_SERVICE_PORT=25
                   MAIL_SERVICE=gmail
                   # sender
                   MAIL_AUTH_USER=onboard.2912@gmail.com
                   # sender password
                   MAIL_AUTH_PASS=VCOTesting123
                   # auth method
                   MAIL_AUTH_METHOD=PLAIN
                   # RECEIVER
                   MAIL_TEST_RECEIVER=onboard.2912@gmail.com

                   MAIL_CC_LIST=alfred.alfie123@gmail.com
                   MAIL_ALERT_CC_LIST=alfred.alfie@jinformation.net,alfred.alfie123@gmail.com
                      #MAIL_AUTH_USER=optus.networks.oss@gmail.com
                     #MAIL_AUTH_PASS=Today123
                   INTEGRATION_SERVICE=http://localhost:3003
                   BASE_URL=http://localhost:3000
                   OPTUS_APPROVAL_BASE_URL=http://localhost:3012

                   IS_PORT=3003
                     #IS_MONGODB_URI=mongodb://localhost:27017/gpm-is
                   INCOME_DIR=prj/optus/gap-data/income-dev
                   INPROGRESS_DIR=prj/optus/gap-data/inprogress-dev
                   RESULT_DIR=prj/optus/gap-data/result-dev
                   RESOURCE_DIR=prj/optus/gap-data/resource-dev

                   # Jira connection related properties
                   JIRA_PROTOCOL=https
                   JIRA_HOST=ossdevdefects.atlassian.net
                   JIRA_PORT=443
                   JIRA_USER=tsaasp@gmail.com
                    # use api token instead of password
                   JIRA_PASSWORD=QE26b5YAY6Gs8Qwqiv8wDD9F
                   JIRA_API_VERSION=3
                   JIRA_CONNECT_STRICT_SSL=true

                   JIRA_GROUP_NAME=Genesis Account Provisioning Nokia
                   JIRA_ADD_PROJECT_KEY=GAP
                   JIRA_REVOKE_PROJECT_KEY=GPP
                     #JIRA_PROTOCOL=http
                    #JIRA_HOST=gdwgnpappl002.optus.com.au
                    #JIRA_PORT=8180
                      #JIRA_USER=cp558846
                   #JIRA_PASSWORD=Gustmd12#
                   #JIRA_API_VERSION=2
                   INTEGRATION_MODE=simulation
                   LDAP_URL=ldap://sydhubdcs.optus.com.au:389
                   LDAP_USERNAME=cp558846
                   LDAP_PASSWORD=Gustmd12#
                   #LOGIN_METHOD=local
                   LOGIN_METHOD=ldap
                   IS_CLICK_FINAL_BUTTON=
                   HEADLESS_MODE=1

                     #VCO
                   SIMULATION_EMPID=CP698366
                   VDI_AUTOMATION_RESULT=prj/optus/gap-data/vdi-result-dev
                   UAM_REPORT_DIR=prj/optus/gap-data/uam-report-dev
                   UAM_FETCH_RESULT=prj/optus/gap-data/uam-report-dev/uamResultFetch.json
                   TIME_TO_GET_UAM_UPDATE=1 minute
                   TIME_TO_GET_CRIMS_UPDATE=2 hours
                   TIME_TO_UPDATE_ACCOUNT_CREATION_STATUS=2 minutes
                   TIME_TO_GENERATE_SOW=1 minute
                   TIME_TO_GET_SOW_RESPONSE=2 minutes
                   TIME_TO_CREATE_VDI_ACCOUNT_JOBS=1 minute
                   TIME_TO_CREATE_VDI_ACCOUNT=in 60 minutes
                   TIME_TO_CREATE_APPLICATION_ACCOUNT=1 minute
                   TIME_TO_CREATE_SM9_JIRA=2 minutes
                   TIME_TO_UPDATE_PADLOCK_STATUS=1 minute
                   TIME_TO_CHECK_APPROVE_MANAGER_EXCEEDS_5_DAYS=24 hours

                   PADLOCK_BASE_URL=https://10.118.3.121:443
                   PADLOCK_X_USERNAME=vco-padlock
                   PADLOCK_X_PASSWORD=$2y$12$AxIpgL.F0svuFHgqLeHIVeFUbQpiTSDAPQ.y.2WLSdw82WIXpJguq
                       # Processing user failed from UAM System: Jira task creation properties
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: package-json-config
data:
  package.json: |
    {
                 "name": "gen-account-provisioning",
                 "version": "1.4.0",
                 "description": "Genesis Profile Management",
                 "_moduleAliases": {
                 "@shared/*": "dist/gpm-client/src/shared/*"
                  },
                  "scripts": {
                  "clean": "rimraf dist",
                   "setupbuild": "ln -hsF ../client/src/shared ./src",
                   "start": "npm run serve",
                    "start-is": "npm run serve-is",
                   "server-build": "npm run build-ts && npm run tslint && npm run copy-static-assets",
                   "server-build-development": "webpack --define process.env.BUILD_PRODUCTION=true --mode development --progress",
                   "server-build-prod": "NODE_ENV=production webpack --define process.env.BUILD_PRODUCTION=true --mode development --progress",
                   "build": "env-cmd ./gpm-client/.env.production npm run client-build && npm run server-build",
                   "build-development": "env-cmd ./client/.env.development npm run client-build && npm run server-build-development",
                   "build-staging": "env-cmd ./client/.env.staging npm run client-build && npm run server-build",
                   "build-test": "env-cmd ./client/.env.test npm run client-build && npm run server-build",
                   "build-vco": "env-cmd ./client/.env.vco npm run client-build && npm run server-build",
                   "build-prod": "env-cmd ./client/.env.development npm run client-build && npm run server-build",
                   "prebuild-development": "npm run clean",
                   "prebuild-prod": "npm run clean",
                   "serve": "./start-all-prod.sh",
                   "serve-is": "node dist/src/is-server.js",
                   "watch-node": "nodemon dist/src/server.js",
                   "watch": "concurrently -k -p \"[{name}]\" -n \"TypeScript,Node\" -c \"yellow.bold,cyan.bold,green.bold\" \"npm run watch-ts\" \"npm run watch-node\"",
                   "test": "jest --forceExit --coverage --verbose",
                   "build-ts": "tsc",
                   "watch-ts": "tsc -w",
                   "tsc-ver": "tsc -v",
                   "tslint": "tslint -c tslint.json -p tsconfig.json",
                   "copy-static-assets": "node copyStaticAssets.js",
                   "serve-debug": "nodemon --inspect dist/src/server.js",
                   "watch-debug": "concurrently -k -p \"[{name}]\" -n \"TypeScript,Node\" -c \"yellow.bold,cyan.bold,green.bold\" \"npm run watch-ts\" \"npm run serve-debug\"",
                   "watch-build": "concurrently -k -p \"[{name}]\" -n \"TypeScript\" -c \"yellow.bold,cyan.bold,green.bold\" \"npm run watch-ts\"",
                   "debug": "npm run server-build && npm run watch-debug",
                   "dev": "npm run server-build && npm run watch",
                   "predev": "npm run copy-static-assets",
                   "test-server": "NODE_ENV=test npm run server-build && NODE_ENV=test npm start",
                   "client-start": "node client-start.js",
                   "client-build": "node client-build.js",
                   "pretest-server": "ts-node dumpDatabase.ts"
                   },
                   "author": "",
                   "license": "ISC",
                   "dependencies": {
                   "agenda": "^2.0.2",
                   "async": "^2.6.0",
                   "axios": "^0.20.0",
                   "bcrypt-nodejs": "^0.0.3",
                   "bluebird": "^3.5.1",
                   "body-parser": "^1.18.2",
                   "boom": "^7.2.0",
                   "cache-manager": "^3.2.1",
                   "chokidar": "^2.0.4",
                   "clone": "^2.1.1",
                   "compression": "^1.7.1",
                   "connect-mongo": "^2.0.1",
                   "dompurify": "^1.0.3",
                   "dotenv": "^4.0.0",
                   "env-cmd": "^8.0.2",
                   "errorhandler": "^1.5.0",
                   "exceljs": "^1.15.0",
                   "express": "^4.16.3",
                   "express-fileupload": "^0.4.0",
                   "express-session": "^1.15.6",
                   "express-validator": "^4.3.0",
                   "fast-csv": "^2.4.1",
                   "fs-extra": "^9.0.0",
                   "gpm-client": "file:gpm-client",
                   "imap-simple": "^4.3.0",
                   "jira-client": "^6.4.1",
                   "jsdom": "^11.6.2",
                   "json2csv": "^4.5.4",
                   "ldapjs": "^1.0.2",
                   "lodash": "^4.17.4",
                   "lusca": "^1.5.2",
                   "module-alias": "^2.2.1",
                   "moment": "^2.20.1",
                   "mongodb-memory-server": "^1.9.3",
                   "mongoose": "^5.4.16",
                   "mongoose-aggregate-paginate-v2": "^1.0.4",
                   "mongoose-beautiful-unique-validation": "^7.1.1",
                   "mongoose-paginate-v2": "^1.3.0",
                   "morgan": "^1.9.0",
                   "nanoid": "^3.1.10",
                   "nodemailer": "^4.6.3",
       "oracledb": "^4.1.0",
       "passport": "^0.4.0",
       "passport-local": "^1.0.0",
       "passport-local-mongoose": "^5.0.0",
       "pug": "^2.0.4",
       "puppeteer": "^2.0.0",
       "query-string": "^6.13.1",
       "request": "^2.85.0",
       "request-promise": "^4.2.2",
       "s": "^0.1.1",
       "shortid": "^2.2.15",
       "socket.io": "^2.3.0",
       "ssh2-sftp-client": "^4.3.0",
       "tsconfig-paths-webpack-plugin": "^3.2.0",
       "webpack": "^4.29.6",
       "webpackbar": "^4.0.0",
       "yargs": "^14.2.0"
       },
      "devDependencies": {
       "@types/agenda": "^2.0.6",
       "@types/async": "^2.0.48",
       "@types/bcrypt-nodejs": "0.0.30",
       "@types/bluebird": "^3.5.18",
       "@types/body-parser": "^1.16.8",
       "@types/boom": "^7.2.0",
       "@types/cache-manager": "^2.10.2",
       "@types/chokidar": "^1.7.5",
       "@types/compression": "0.0.33",
       "@types/dotenv": "^4.0.2",
       "@types/errorhandler": "0.0.32",
       "@types/exceljs": "^0.5.3",
       "@types/express": "^4.11.1",
       "@types/express-fileupload": "^0.1.1",
       "@types/express-session": "^1.15.6",
       "@types/fs-extra": "^8.1.0",
       "@types/jest": "^21.1.8",
       "@types/jquery": "^3.3.1",
       "@types/json2csv": "^4.5.1",
       "@types/lodash": "^4.14.105",
       "@types/lusca": "^1.5.0",
       "@types/mongodb-memory-server": "^1.8.0",
       "@types/mongoose": "^5.7.1",
       "@types/mongoose-paginate-v2": "^1.0.3",
       "@types/morgan": "^1.7.32",
       "@types/nanoid": "^2.1.0",
       "@types/node": "^12.6.8",
       "@types/nodemailer": "^1.3.32",
       "@types/oracledb": "^4.1.1",
       "@types/passport": "^0.4.3",
       "@types/passport-local": "^1.0.32",
       "@types/passport-local-mongoose": "^4.0.11",
       "@types/pug": "^2.0.4",
       "@types/puppeteer": "^1.6.4",
       "@types/request": "^2.0.9",
       "@types/shelljs": "^0.7.7",
       "@types/socket.io": "^2.1.4",
       "@types/ssh2-sftp-client": "^4.1.2",
       "chai": "^4.1.2",
        "concurrently": "^3.5.1",
       "node-sass": "^4.8.3",
        "nodemon": "^1.17.2",
        "rimraf": "^3.0.2",
        "shelljs": "^0.7.8",
       "simple-git": "^2.4.0",
       "ts-jest": "^21.2.4",
       "ts-loader": "^7.0.4",
       "ts-node": "^4.0.2",
       "tslint": "^5.8.0",
       "typescript": "^3.5.3",
       "webpack-cli": "^3.3.11",
       "winston": "^2.4.4"
      }
     }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: start-all-config
data:
  start-all-dev.sh: |
    NODE_ENV=development pm2 start dist/src/server.js --name "gpm-prod"
                         NODE_ENV=development pm2 start dist/src/cmd/vco/cronjobs/applicationAccountCreation.js --name "app-creation-prod"
                         NODE_ENV=development pm2 start dist/src/cmd/vco/cronjobs/sow.js --name "sow-prod"
                         NODE_ENV=development pm2 start dist/src/cmd/vco/cronjobs/parseUAMReport.js --name "uamReport-prod"
                         NODE_ENV=development pm2 start dist/src/cmd/vco/cronjobs/createSM9Jira.js --name "sm9-prod"
                         NODE_ENV=development pm2 start dist/src/cmd/vco/cronjobs/vdiAccountCreation.js --name "vdi-prod"
                         NODE_ENV=development pm2 start dist/src/cmd/vco/cronjobs/updatePadlockStatus.js --name "padlock-prod"
                         NODE_ENV=development pm2 start dist/src/is-server.js --name "is-server"
                         NODE_ENV=development pm2 logs

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: start-prod-config
data:
  start-all-prod.sh: |
    NODE_ENV=production pm2 start dist/src/server.js --name "gpm-prod"
    NODE_ENV=production pm2 start dist/src/cmd/vco/cronjobs/applicationAccountCreation.js --name "app-creation-prod"
    NODE_ENV=production pm2 start dist/src/cmd/vco/cronjobs/sow.js --name "sow-prod"
    NODE_ENV=production pm2 start dist/src/cmd/vco/cronjobs/parseUAMReport.js --name "uamReport-prod"
    NODE_ENV=production pm2 start dist/src/cmd/vco/cronjobs/createSM9Jira.js --name "sm9-prod"
    NODE_ENV=production pm2 start dist/src/cmd/vco/cronjobs/vdiAccountCreation.js --name "vdi-prod"
    NODE_ENV=production pm2 start dist/src/cmd/vco/cronjobs/updatePadlockStatus.js --name "padlock-prod"
    NODE_ENV=production pm2 start dist/src/is-server.js --name "is-server"
    NODE_ENV=development pm2 logs
